[package]
name = "ccon"
version = "0.1.0"
authors = ["Randeep Dhaliwal <dhaliwal.randeep.s@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["json"] }
tokio = { version = "0.2", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }