[package]
name = "ccon"
version = "0.1.0"
authors = ["Randeep Dhaliwal <dhaliwal.randeep.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
